### ISSUE TITLE
csvファイル作り

### ISSUE THREAD

**Issue by tomokinex** [tomokinex/training#1]
ごはん休みの日のcsv
 メニューのcsv 
namelist.csvを全員分記入 
部屋番号_list.csvを全員分作成

全部なんらかの値はいれといて動くようにしたい

**Comment by tomokinex** [comment]
休みの日のcsvにとりあえず今年の祝日にだけbit立ててつくった
fes_list.csv

**Comment by tomokinex** [comment]
menu_list.csvも作成

**Comment by tomokinex** [comment]
おのおののlistも12×31でやるよりも12×62でやったほうが統一感があってよさそう？

**Comment by tomokinex** [comment]
あとこれができたら稼働できるのでやってくれー

**Comment by yutarouenoyama** [comment]
おそらくできました

2017年9月27日(水) 18:01 Tomoki Nakamura <notifications@github.com>:

**Comment by tomokinex** [comment]
終わり！
