### ISSUE TITLE
初期化のscript

### ISSUE THREAD

**Issue by tomokinex** [tomokinex/training#12]
今の仕様で困りそうなこと
1 注文の有無のファイルが月単位で入力しているので,一年前のやつが初期値となってしまう
2 乞食ボタンも一日単位なので,前日の値が初期値となってしまう

上記の0初期化を**適切な**タイミングで実行するスクリプトを回したい

**Comment by jseb93** [comment]
1の注文に関しては初期化とバックアップのscriptが完成．
あとはraspi側からcronでスケジューリングすれば良い．
月を指定して初期化するように実装したので，部分的な初期化が可能．
とりあえず半年ごとにファイルを半分書き換えるのが良さそう？

**Comment by tomokinex** [comment]
乞食ボタンが説明読まない人間晒上げボタンと化していたので,とりあえず削除
ブランチ切って保存しているので必要であれば復元できる.

**Comment by tomokinex** [comment]
バックアップ用のgit pushが失敗していたので原因を調査したところ,data以下の権限がまたリセットされていた.
すこし乱暴だが,crontabで定期的にもしくはgit 関連のコマンド使用時にchmodを掛けるようなscript書いたほうがいい？

**Comment by tomokinex** [comment]
crontabが働いてなさそうなので調べてみたところ,シェルスクリプトに実行権限がないことが原因っぽいです.
csvと同様の現象っぽい？新しいファイル作成時に付与される権限の制限がきつそう

**Comment by tomokinex** [comment]
解決しなかった・・・

**Comment by jseb93** [comment]
多分解決．
cron実行時にログイン状態のパスが反映されないことが原因でした．
絶対パスで実行ファイルを指定すると，1分刻みでは動作しました．
今晩動くか確認しましょう．

今後のエラー処理のために
/home/pi/logにcrontabの標準出力・標準エラー出力のログを吐き出すようにしました．
