### ISSUE TITLE
dataの権限

### ISSUE THREAD

**Issue by tomokinex** [tomokinex/training#14]
raspberryでgit pullするとdataの書き込み権限がなくなってしまう

**Comment by jseb93** [comment]
下記の方法で解決できそう．
https://qiita.com/yuuAn/items/b1d1df2e810fd6b92574

**Comment by jseb93** [comment]
すでにcommit済みのファイルをgit管理対象から外す方法
各自の環境でdata以下のファイルを管理対象から除外する場合
$ find syokudo/data -type f | xargs git update-index --skip-worktree
ローカルの変更が無視されるだけでなく，リモートで変更があってもローカルの状態が優先されるらしい．
とりあえずraspi上でmasterブランチに適用し，ファイル変更が無視されるのを確認済み．
これでraspi上でpullしてdataが書き換わる心配はないはず．

参考サイト：
https://qiita.com/usamik26/items/56d0d3ba7a1300625f92
