### ISSUE TITLE
編集機能

### ISSUE THREAD

**Issue by jseb93** [tomokinex/training#18]
注文データの編集機能を実装完了．
管理人の集計ページから前月，今月，来月分の注文データを編集可能．

**Comment by tomokinex** [comment]
ふと気づいたのですが,複数のページから同一のファイルを読み込みだけでなく書き込みを可能にすると,
ファイル書き込み時のコンフリクトはロックで起こりませんが,前回読み込んだファイル情報を保持したままブラウザを開きっぱなしにしていて,時間差で書き込みが起こった場合に,間に他ページで書き込んだ情報が消えるってことが起こり得ませんか？

**Comment by tomokinex** [comment]
けっこう伝え忘れていましたが,編集画面のレイアウトが崩れてるようです
僕の環境でも崩れてました
