### ISSUE TITLE
webサーバ構築完了

### ISSUE THREAD

**Issue by jseb93** [tomokinex/training#9]
食堂ネットワーク上のraspiにwebサーバ構築完了．
153.169.40.122:8080 から外部アクセス可能です．

**Comment by tomokinex** [comment]
sshしたいんで、readmeとかにprivate addressを書き込んでほしいです＞＜
pass変えてるんだったら直接ききます

**Comment by jseb93** [comment]
了解です．
IPは172.16.0.3でローカルからのみssh接続可能な状態です．
passは口頭で教えるので聞いてください．

**Comment by jseb93** [comment]
readme更新しました．
